feat: Added get available currencies endpoint
pillarex/platform-cashier-service pull request #1
Opened 2024-07-01 12:44 UTC by michal-stybowski-ft

Added new endpoint for returning a list of available currencies

2024-07-01 21:33 UTC, mikefuntico requested changes
See my 2 comments, overall lgtm

2024-07-01 21:33 UTC, mikefuntico commented on src/domain/currencies/consts.ts
I would suggest to create an object enum as
```ts
const TransactionCurrencyType = {
  Fiat: 'fiat',
  Crypto: 'crypto'
} as const
```

2024-07-01 21:33 UTC, mikefuntico commented on src/domain/currencies/wertSupportedCryptoCurrencies.ts
do we need to hard code these? It might not be a bad idea but I want to know why you decided to go with that

2024-07-02 08:10 UTC, michal-stybowski-ft commented on src/domain/currencies/wertSupportedCryptoCurrencies.ts
Wert doesn't provide any endpoint to get supported currencies.

2024-07-02 08:24 UTC, michal-stybowski-ft commented on src/domain/currencies/wertSupportedCryptoCurrencies.ts
Btw. we dont use it for now.

2024-07-02 09:32 UTC, merged