feat(integrations): add integrations
pillarex/platform-cashier-service pull request #5
Opened 2024-07-03 12:34 UTC by NikitaFedorov1

2024-07-03 12:58 UTC, michal-stybowski-ft commented
<img width="990" alt="image" src="https://github.com/pillarex/platform-cashier-service/assets/170326455/d23e24c4-c4dc-4883-add9-0f63f8d96ffe">
Are you sure you added required ts config to support the new folder?

2024-07-03 12:58 UTC, michal-stybowski-ft requested changes
What's the rationale behind creating integrations folder when we already have libs folder just for such standalone packages? 
Aditionally, For such big changes at least 2 tests per package is a must.

apart from that, nice work.

2024-07-03 12:58 UTC, michal-stybowski-ft commented on lib/std/index.ts
Why we need that?

2024-07-03 12:58 UTC, michal-stybowski-ft commented on lib/std/package.json
Why we need 1 liner library?

2024-07-03 12:58 UTC, michal-stybowski-ft commented on src/http/index.register.ts
> +    const fetcher = createFetcher();
This setup should go to `src/deps/global.ts` and services should be part of AppDeps in `src/app.ts` next to env.

2024-07-03 12:58 UTC, michal-stybowski-ft commented on src/http/availableCurrencies/availableCurrencies.ctrl.ts
> +        simplex;
why?

2024-07-03 12:58 UTC, michal-stybowski-ft commented on src/http/availableCurrencies/availableCurrencies.ctrl.ts
> +    services: { simplex },
dont nest it. 
```suggestion
    env, 
    simplex,
    nowPayments
```

2024-07-03 12:58 UTC, michal-stybowski-ft commented on .eslintrc.cjs
> +          Object.assign({}, restrictedImports, {
whats the reason?

2024-07-03 13:03 UTC, NikitaFedorov1 commented
> <img alt="image" width="990" src="https://private-user-images.githubusercontent.com/170326455/345429969-d23e24c4-c4dc-4883-add9-0f63f8d96ffe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMTE5MTQsIm5iZiI6MTcyMDAxMTYxNCwicGF0aCI6Ii8xNzAzMjY0NTUvMzQ1NDI5OTY5LWQyM2UyNGM0LWM0ZGMtNDg4My1hZGQ5LTBmNjNmOGQ5NmZmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxMzAwMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTg3ZTUxZjNkMTc2OGViNWE4OTM2OTY4YzIyNGU5OGY0ODBjOTQ5NjlkODcwMjVkNzcyZjI1YjcyMzA4MDIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8ostTs-yobXFQUhKm9WzBychSblDfUV8uiZy-AZPkJ8"> Are you sure you added required ts config to support the new folder?

u need to
```
docker-compose run --rm api npm i
```
because it's `package.json` module resolution, not the typescript one. Later we can use project refs instead.

2024-07-03 13:18 UTC, NikitaFedorov1 commented on .eslintrc.cjs
> +          Object.assign({}, restrictedImports, {
It's removed now. And `.cjs` added to eslint parser config.

2024-07-03 13:20 UTC, NikitaFedorov1 commented on src/http/availableCurrencies/availableCurrencies.ctrl.ts
> +        simplex;
it's instead of `unused`, just to check that it's fine.

2024-07-03 13:26 UTC, NikitaFedorov1 commented on lib/std/package.json
to isolate external dependencies, for example this library cannot be used without a wrapper because its exports are not named

2024-07-03 13:47 UTC, michal-stybowski-ft commented on lib/std/package.json
I understand but this is not the reason to create a npm package wrapper. Please align.

2024-07-03 15:42 UTC, NikitaFedorov1 commented on src/http/index.register.ts
> +    const fetcher = createFetcher();
I use this fetcher instead of CircultBracker fetcher for a while. I moved the initialization of services to `deps`, we must create them in the root plugin for routes so that we can load them asynchronously in the future, so I added them to `src/app.ts` as u said.

2024-07-03 15:42 UTC, NikitaFedorov1 commented on src/http/availableCurrencies/availableCurrencies.ctrl.ts
> +    services: { simplex },
done

2024-07-04 15:19 UTC, NikitaFedorov1 commented on lib/std/package.json
Ideally, all external dependencies should be provided via dependency injection, because their variation is always greater than 2, and wrapped in adapters if possible because they change regardless of use. Language-level dependencies are usually provided statically because their variation is close to zero, and are wrapped in adapters to maintain language consistency.

2024-07-04 15:23 UTC, NikitaFedorov1 commented on lib/std/index.ts
As you said, these are not static libraries, but adapters that use static libraries.

2024-07-05 09:59 UTC, michal-stybowski-ft commented on lib/std/index.ts
not really, env is the only lib that is modifiable. the rest are static.

2024-07-05 10:02 UTC, michal-stybowski-ft commented on lib/std/package.json
What makes js-big-decimal different than other libraries so that only this one is wrapper? Is it not named export?

2024-07-05 10:09 UTC, michal-stybowski-ft approved these changes

2024-07-05 10:10 UTC, merged